"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SqlType = void 0;
var SqlType;
(function (SqlType) {
    SqlType["VarChar"] = "VarChar";
    SqlType["NVarChar"] = "NVarChar";
    SqlType["Text"] = "Text";
    SqlType["Int"] = "Int";
    SqlType["BigInt"] = "BigInt";
    SqlType["TinyInt"] = "TinyInt";
    SqlType["SmallInt"] = "SmallInt";
    SqlType["Bit"] = "Bit";
    SqlType["Float"] = "Float";
    SqlType["Numeric"] = "Numeric";
    SqlType["Decimal"] = "Decimal";
    SqlType["Real"] = "Real";
    SqlType["Date"] = "Date";
    SqlType["DateTime"] = "DateTime";
    SqlType["DateTime2"] = "DateTime2";
    SqlType["DateTimeOffset"] = "DateTimeOffset";
    SqlType["SmallDateTime"] = "SmallDateTime";
    SqlType["Time"] = "Time";
    SqlType["UniqueIdentifier"] = "UniqueIdentifier";
    SqlType["SmallMoney"] = "SmallMoney";
    SqlType["Money"] = "Money";
    SqlType["Binary"] = "Binary";
    SqlType["VarBinary"] = "VarBinary";
    SqlType["Image"] = "Image";
    SqlType["Xml"] = "Xml";
    SqlType["Char"] = "Char";
    SqlType["NChar"] = "NChar";
    SqlType["NText"] = "NText";
    SqlType["TVP"] = "TVP";
    SqlType["UDT"] = "UDT";
    SqlType["Geography"] = "Geography";
    SqlType["Geometry"] = "Geometry";
    SqlType["Variant"] = "Variant";
})(SqlType = exports.SqlType || (exports.SqlType = {}));
//# sourceMappingURL=SqlType.js.map